### ISSUE TITLE
Built files and dependencies added to git

### ISSUE THREAD

**Issue by tomalrussell** [souzamonteiro/cnatool#3]
This is a general code/repository review comment.

I would consider removing all of the following files from git:
- files that can be specified as dependencies (`node_modules`, `sigma.js-1.2.1.zip`, `tmp`, some of `js`)
- files that can be built from the source code ( some of `js`, `docs`, `build`, `bin`)
- duplicate copies (`manual/*` is copied and versioned under `docs/`)
- files that aren't otherwise used here (`fonts/maya-allstars-font.zip`, `images/{cloud,liza}*`)
- test outputs (`test.txt`, `test/test.html`?)
- unused submodules (`.gitmodules` has https://github.com/a-nsilva/joss-CNATool twice, but the content has moved into this repository with more recent changes)

If possible, also avoid the duplication of built files - do we need all of `src`, `js` and `bin`?

Could `maiascript` and `libmaia` be specified as dependencies and installed or required?

This would make it easier for a reviewer or new contributor to orient themselves and focus on the most important files in the repository.

**Comment by souzamonteiro** [comment]
Hello:
I removed the node_modules directory and copies of the manual from the docs directory. The manual folder exists to meet the needs of other magazines that ask for this folder so I will have to leave the manuals in it. The sigma.js-1.2.1.zip file will remain because I use this particular version of the package and don't want users to use another one that I can't guarantee will work. The other directories I find useful as well as the test reports because I often need these results on github for several reasons. The js, src etc directories are used in the online version and not all users are able to recreate them, so I decided to keep them as well. Thanks for the comments. maiascript and libmaia are not dependencies that can be installed automatically as CNATOOL uses these specific versions of the libraries and not those available in the npm repository. They are there to ensure that graduate students using the tool can run it directly when downloading from github.

**Comment by tomalrussell** [comment]
Hi @souzamonteiro, thanks for taking a look at this, and explaining the need for some things to be included here.

Great, keeping the `manuals` directory makes sense.

It looks like the deletion of [`node_modules`](https://github.com/souzamonteiro/cnatool/tree/b23764e93acb7d7d55fe5e2a144fe6242404a279/node_modules) still needs to be pushed to `main` 

For info, `sigma.js` v1.2.1 can be installed reliably with `npm install sigma@1.2.1 --save-dev`, with minified files built and saved for you in `node_modules/sigma/build/`. You could for example consider removing `tmp` and `sigma.js-1.2.1.zip` and `js/sigma.js` and replacing them with a copy of those minified files - that would let you shorten the long list of `<script...` tags in `index.html` too, and would retain the benefits of having the library commited and versioned in this repository.

Okay, I acknowledge the need for `maiascript` and `libmaia` to be vendored and included to pin to specific versions.

Do you still need those files that aren't referenced anywhere else (fonts/maya-allstars-font.zip, images/{cloud,liza}*) or the unused submodules (.gitmodules)?

**Comment by souzamonteiro** [comment]
> Hi @souzamonteiro, thanks for taking a look at this, and explaining the need for some things to be included here.
> 
> Great, keeping the `manuals` directory makes sense.
> 
> It looks like the deletion of [`node_modules`](https://github.com/souzamonteiro/cnatool/tree/b23764e93acb7d7d55fe5e2a144fe6242404a279/node_modules) still needs to be pushed to `main`
> 
> For info, `sigma.js` v1.2.1 can be installed reliably with `npm install sigma@1.2.1 --save-dev`, with minified files built and saved for you in `node_modules/sigma/build/`. You could for example consider removing `tmp` and `sigma.js-1.2.1.zip` and `js/sigma.js` and replacing them with a copy of those minified files - that would let you shorten the long list of `<script...` tags in `index.html` too, and would retain the benefits of having the library commited and versioned in this repository.
> 
> Okay, I acknowledge the need for `maiascript` and `libmaia` to be vendored and included to pin to specific versions.
> 
> Do you still need those files that aren't referenced anywhere else (fonts/maya-allstars-font.zip, images/{cloud,liza}*) or the unused submodules (.gitmodules)?

sygma.js is a GUI dependency and not a command line tool. The graphical interface runs directly in the browser and does not need to be installed. The sygma is provided as it is so that users who want to can run the program simply by downloading and unzipping it from github and double clicking on the index.html file. It would not be useful to place it as a dependency and would even reduce the ease of installation. Most users are from the sociology area and do not understand anything about programming and would not know how to perform the necessary steps. For this reason I choose to keep the sygma.js library inside the package, as it is now. Thanks for the suggestion.

**Comment by tomalrussell** [comment]
Okay, it does make sense in that case to keep a copy of the GUI script dependencies. There would still be advantages in terms of number and size of files, if you included the minified built files, rather than a full copy of the library in both `./tmp` and `./js/sigma.js`. Saving `sigma@1.2.1` as a development dependency (which is what `--save-dev` does) would allow developers of the tool to install (and eventually update) the library automatically, without forcing it on users. Reducing the number of files should make it easier for non-expert users to find the most relevant files, and not be confused by unnecessary or unused files.

I'd still recommend removing: 
- files that aren't referenced anywhere else (fonts/maya-allstars-font.zip, images/{cloud,liza}*) 
- the unused submodules (.gitmodules)
- the [node_modules](https://github.com/souzamonteiro/cnatool/tree/b23764e93acb7d7d55fe5e2a144fe6242404a279/node_modules) directory

**Comment by souzamonteiro** [comment]
> Okay, it does make sense in that case to keep a copy of the GUI script dependencies. There would still be advantages in terms of number and size of files, if you included the minified built files, rather than a full copy of the library in both `./tmp` and `./js/sigma.js`. Saving `sigma@1.2.1` as a development dependency (which is what `--save-dev` does) would allow developers of the tool to install (and eventually update) the library automatically, without forcing it on users. Reducing the number of files should make it easier for non-expert users to find the most relevant files, and not be confused by unnecessary or unused files.
> 
> I'd still recommend removing:
> 
> * files that aren't referenced anywhere else (fonts/maya-allstars-font.zip, images/{cloud,liza}*)
> * the unused submodules (.gitmodules)
> * the [node_modules](https://github.com/souzamonteiro/cnatool/tree/b23764e93acb7d7d55fe5e2a144fe6242404a279/node_modules) directory

Hello:

I removed the fonts and images directories and the .gitmodules file. I also include the node_modules directory in the .gitignore file. I modified the build.sh script to copy the sygma.js files from the node_modules/sigma/build directory to the js directory and modified the index.html file to use the minified versions of the scripts in sigma.js.
